### ISSUE TITLE
Support combination of keys (e.g., ⌘+K)

### ISSUE THREAD

**Issue by EwenQuim** [metonym/svelte-focus-key#8]
Hello, I would like to know if this tool supports multiple keys trigger, like cmd+K or ctrl+K ? Thanks

**Comment by metonym** [comment]
Currently, it does not support a combination of keys. It definitely should since CMD+K is so common now – marking this as a feature request.

**Comment by metonym** [comment]
Combo keys are now supported in version 1.0.0.

Combo keys should be delimited by a `+` symbol.

```svelte
<script>
  import FocusKey from "svelte-focus-key";

  let element;
</script>

<input bind:this={element} placeholder={'Press "⌘+k" to focus'} />

<FocusKey {element} key="Meta+k" />

```
